# Default Opsimate Configuration
# This configuration is built into the Docker image and used when no custom config is provided

# Server configuration
server:
  port: 3001
  host: "0.0.0.0"  # Bind to all interfaces in container

# Database configuration
database:
  path: "/app/data/database/opsimate.db"  # Container path

# Security configuration
security:
  private_keys_path: "/app/data/private-keys"  # Container path for SSH keys

# Logging configuration
logging:
  # Default limits for fetching container and service logs
  rowLimit: 100              # Maximum number of log lines to retrieve per request
  sizeLimitMB: 10            # Maximum total size of logs to fetch (in MB)
  includeErrors: false       # If false, filters logs to show only errors/warnings/critical messages

# mailer configuration
mailer:
  enabled: true
  default_encoding: "UTF-8"
  host: "smtp.gmail.com"
  port: 587                
  secure: false             
  from: "<no-reply@yourdomain.com>"
  replyTo: "ops@yourdomain.com"
  auth:
    user: "<Gmail username>"
    pass: "<Gmail password>"        
  tls:
    rejectUnauthorized: true
